#!/bin/bash

# print name script
echo $0

# print all arguments
echo $*

# print the number of arguments passed to the script
echo $#

# print 2nd and 4th argument
echo ${2} ${4}

if [[ ${1} -eq  ${2} ]]; then
	echo 0 
else
	echo 1
fi


